#!/usr/bin/expect -f
set timeout 10
set HOST "46.202.161.37"
set PORT "65002"
set USER "u555641943"
set PASSWORD "Kw4kN#uqnW.#KJw"

spawn ssh -o StrictHostKeyChecking=no -p $PORT $USER@$HOST {mysql -u u555641943_tcap -p'Kw4kN#uqnW.#KJw' u555641943_tcap -e "SELECT blog_id, SUBSTRING(name,1,60) as name, slug, date FROM tbl_blog ORDER BY blog_id DESC LIMIT 5;"}
expect "password:"
send "$PASSWORD\r"
expect eof
