#!/usr/bin/expect -f
set timeout 10
set HOST "46.202.161.37"
set PORT "65002"
set USER "u555641943"
set PASSWORD "Kw4kN#uqnW.#KJw"

spawn ssh -o StrictHostKeyChecking=no -p $PORT $USER@$HOST {mysql -u u555641943_tcap -p'Kw4kN#uqnW.#KJw' u555641943_tcap -e "SELECT blog_id, name, slug, focus_keyword, date FROM tbl_blog ORDER BY blog_id DESC LIMIT 3;"}
expect "password:"
send "$PASSWORD\r"
expect eof
